# Generated by Django 3.2.16 on 2023-01-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Adresses"},
        ),
        migrations.AlterField(
            model_name="street",
            name="name_street",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="name_street"
            ),
        ),
    ]
