# Generated by Django 3.2.16 on 2023-01-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_remove_work_user_of_promo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "pfffffff", "verbose_name_plural": "Adresses"},
        ),
    ]
