# Generated by Django 3.2.16 on 2023-01-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_address_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Adresses"},
        ),
    ]
